Versioning
NHGitHub7/DiscordBot pull request #35
Opened 2021-06-14 17:15 UTC by Failpark

Added versioning vgl. commit message.

2021-06-14 17:16 UTC, Failpark commented on DB/DDL.sql
> +DROP TABLE IF EXISTS version;
Vllt. Ohne DROP TABLE ?

2021-06-14 17:17 UTC, Failpark commented on DB/DDL.sql
> +DROP TABLE IF EXISTS customcommands;
Vllt. Ohne DROP TABLE ?

2021-06-15 12:06 UTC, NHGitHub7 requested changes

2021-06-15 12:06 UTC, NHGitHub7 commented on Program.cs
> +      //MainAsync().GetAwaiter().GetResult();
```suggestion
      MainAsync().GetAwaiter().GetResult();
```

2021-06-15 12:16 UTC, NHGitHub7 approved these changes

2021-06-15 12:16 UTC, merged